# Base Configuration for Crawler
# This file contains global settings that apply to the entire application

# Milvus Connection Settings
milvus:
  enabled: true
  secure: false
  host: "localhost"
  port: 19530
  username: "minioadmin"
  password: "minioadmin"
  consistency_level: "Bounded" # Options: Strong, Bounded, Session, Eventual, trade offs of when the data is available across nodes
  index_field: "embedding"
  index_params:
    index_type: "IVF_FLAT"
    metric_type: "L2"
    params:
      nlist: 128

# LLM Settings
llm:
  # model: gemini-2.0-flash
  # provider: "google-genai"
  # base_url: "https://generativelanguage.googleapis.com/v1beta/"
  model: "llama-3.3-70b-versatile" # Default LLM model - must support structured outputs
  provider: "groq" # required for api configuration
  base_url: "https://api.groq.com"
  # model: "gemma3" # Default LLM model - must support structured outputs
  # provider: "ollama" # required for api configuration
  # base_url: "http://localhost:11434"

# Vision LLM Settings
vision_llm:
  # model: gemini-2.0-flash
  # provider: "google-genai"
  # base_url: "https://generativelanguage.googleapis.com/v1beta/"
  model: "gemma3"
  provider: "ollama"
  base_url: "http://localhost:11434"

# Embedding Settings
embeddings:
  model: "all-minilm:v2" # Default embedding model
  provider: "ollama"
  base_url: "http://localhost:11434"
  dimension: 384

# Logging Settings
logging:
  level: "INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "crawler.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Processing Configuration
extractor:
  chunking:
    length:
      enabled: true
      length: 5000 # number of characters per chunk
      overlap: 100 # number of characters to overlap between chunks

    metadata:
      enabled: true

  document_readers:
    - type: "json"
      enabled: false
    - type: "pdf"
      enabled: true
    - type: "text"
      enabled: false
    - type: "markdown"
      enabled: false
    - type: "html"
      enabled: false
    - type: "csv"
      enabled: false
    - type: "docx"
      enabled: false
    - type: "pptx"
      enabled: false
