# Base Configuration for Crawler
# This file contains global settings that apply to the entire application

# Milvus Connection Settings
milvus:
  enabled: true
  secure: false
  host: "localhost"
  port: 19530
  username: "root"
  password: "Milvus"
  consistency_level: "Bounded" # Options: Strong, Bounded, Session, Eventual, trade offs of when the data is available across nodes

# LLM Settings
llm:
  # model: gemini-2.0-flash
  # provider: "google-genai"
  # base_url: "https://generativelanguage.googleapis.com/v1beta/"
  model: "llama-3.3-70b-versatile" # Default LLM model - must support structured outputs
  provider: "groq" # required for api configuration
  base_url: "https://api.groq.com"
  # model: "gemma3" # Default LLM model - must support structured outputs
  # provider: "ollama" # required for api configuration
  # base_url: "http://localhost:11434"

# Vision LLM Settings
vision_llm:
  # model: gemini-2.0-flash
  # provider: "google-genai"
  # base_url: "https://generativelanguage.googleapis.com/v1beta/"
  model: "granite3.2-vision:latest"
  provider: "ollama"
  base_url: "http://localhost:11434"

# Embedding Settings
embeddings:
  model: "all-minilm:v2" # Default embedding model
  provider: "ollama"
  base_url: "http://localhost:11434"
  dimension: 384

# Logging Settings
logging:
  level: "INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "crawler.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Processing Configuration
extractor:
  engine: "markitdown" # Options: docling, markitdown
  metadata: # Using portions of the extracted metadata for extra embeddings
    enabled: true
  chunking:
    enabled: true
    engine: "smart" # Options: smart, length
    chunk_size: 5000 # number of characters per chunk
    overlap: 100 # number of characters to overlap between chunks, used with engine length
  timeout: 300 # seconds
