# Collection Configuration Template
# This template defines the structure for a collection in the vector database

collection: "default_collection" # Collection name
partition: "" # Partition name
description: "Document chunks with embeddings"
recreate: false # Whether to recreate the collection

milvus:
  secure: false # Whether Milvus connection is secure
  username: "" # Milvus username
  password: "" # Milvus password
  allowed_roles: [] # List of allowed users, yourself is always allowed

# Schema Definition
metadata:
  semantic_search: # text already included
    - description
  full_text_search:
    - title
    - author
    - date
    - keywords
    - unique_words
  schema:
    $schema: "http://json-schema.org/draft-07/schema#"
    title: "Document"
    type: "object"
    required: ["title", "author", "date"]
    properties:
      # text:
      #   type: "string"
      #   maxLength: 10240
      #   description: "Text content of the document chunk."
      # embedding:
      #   type: "float_vector"
      #   dim: 384 # Should match the embedding dimension in base_config.yaml
      #   description: "Embedding vector of the document chunk."
      # source:
      #   type: "string"
      #   maxLength: 1024
      #   description: "Source identifier of the document chunk."
      # chunk_index:
      #   type: "integer"
      #   description: "Index of the document chunk."
      title:
        type: "string"
        maxLength: 255
        description: "Title of the document."
      author:
        type: "array"
        items:
          type: "string"
          description: "Author of the document"
          maxLength: 255
        description: "List of authors of the document"
      date:
        type: "integer"
        description: "The publication date of the document."
        minimum: 1900
        maximum: 2100
      description:
        type: "string"
        maxLength: 5120
        description: "Description of the document content"
      keywords:
        type: "string"
        maxLength: 5120
        description: "Keywords associated with the document content"
      unique_words:
        type: "string"
        maxLength: 5120
        description: "Unique words in the document content, things that seem relevant only to insiders."
