# Collection Configuration Template
# This template defines the structure for a collection in the vector database

collection_name: "default_collection" # Collection name
partition_name: "" # Partition name
description: "Document chunks with embeddings"

milvus_security:
  secure: false # Whether Milvus connection is secure
  username: "" # Milvus username
  password: "" # Milvus password
  allowed_roles: [] # List of allowed users, yourself is always allowed

# Schema Definition
metadata:
  extra_embeddings: [] # What extra embeddings to include from the schema keys
  schema:
    $schema: "http://json-schema.org/draft-07/schema#"
    title: "Document"
    type: "object"
    properties:
      # text:
      #   type: "string"
      #   maxLength: 10240
      #   description: "Text content of the document chunk."
      # embedding:
      #   type: "float_vector"
      #   dim: 384 # Should match the embedding dimension in base_config.yaml
      #   description: "Embedding vector of the document chunk."
      source:
        type: "string"
        maxLength: 1024
        description: "Source identifier of the document chunk."
      title:
        type: "string"
        maxLength: 255
        description: "Title of the document."
      author:
        type: "array"
        maxItems: 255
        items:
          type: "string"
          description: "An author of the document."
        description: "List of authors of the document."
      author_role:
        type: "string"
        maxLength: 255
        description: "Role of the author in the document (e.g., writer, editor)."
      url:
        type: "string"
        maxLength: 1024
        description: "URL associated with the document."
      chunk_index:
        type: "integer"
        description: "Index of the document chunk."
