# config/agent_config.yaml

# Main configuration parameters for the Researcher Agent MVP.

llm_settings:
  api_key: "your_llm_api_key_here" # API key for the LLM service
  model_name: "gpt-4" # Model name to be used for query processing
  temperature: 0.7 # Sampling temperature for the LLM
  max_tokens: 1024 # Maximum number of tokens per request

milvus_connection:
  host: "localhost" # Host address of the Milvus server
  port: 19530 # Port number for the Milvus service
  collection_name: "researcher_documents" # Name of the collection for document storage
  connection_pool: true # Enable connection pooling for performance

worker_recursion:
  num_workers: 5 # Default number of worker agents to spawn
  max_recursion_depth: 3 # Maximum allowed recursion depth for sub-queries

security:
  authentication_token: "your_security_token" # Token used for authenticating requests
  roles: ["admin", "user"] # Defined roles for access control

logging:
  log_file: "logs/researcher_agent.log" # Path to the log file
  log_level: "INFO" # Logging level (DEBUG, INFO, WARNING, ERROR)
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" # Format for log messages
