apiVersion: v2
name: internal-perplexity
description: AI Platform with Open WebUI, Ollama, and Milvus
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: open-webui
    version: ~1.0.0
    repository: https://charts.openwebui.com/
    condition: open-webui.enabled
  - name: ollama
    version: ~1.0.0
    repository: https://charts.ollama.ai/
    condition: ollama.enabled
  - name: milvus
    version: ~2.2.8
    repository: https://milvus-io.github.io/milvus-helm/
    condition: milvus.enabled
