# Global configuration
global:
  storageClass: standard
  registry: docker.io

# Open WebUI configuration
open-webui:
  enabled: true
  replicaCount: 1
  image:
    repository: openwebui/open-webui
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: webui.local
        paths:
          - path: /
            pathType: Prefix
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  pipelines:
    enabled: true
  ollama:
    enabled: false
  persistence:
    enabled: true
    size: 10Gi

# Ollama configuration
ollama:
  enabled: true
  replicaCount: 1
  image:
    repository: ollama/ollama
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 11434
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 8Gi
  persistence:
    enabled: true
    size: 20Gi
  models:
    - name: gemma3

# Milvus configuration
milvus:
  enabled: true
  standalone:
    enabled: true
  cluster:
    enabled: false
  etcd:
    replicaCount: 1
  minio:
    mode: standalone
  pulsar:
    enabled: false
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  persistence:
    enabled: true
    size: 20Gi
