# Directory-specific configuration for conference data
path: "../../data/conference"

# Override specific collection parameters
collection: "conference"
description: "Conference documents and papers with embeddings"

milvus:
  username: "minioadmin"
  password: "minioadmin"

# You can override specific schema fields if needed
metadata:
  extra_embeddings:
    - description
