# Directory-specific configuration for conference data
path: "../../data/sample"

# Collection to use for this directory
collection: "sample"
partition: "test"

milvus:
  username: "minioadmin"
  password: "minioadmin"

# You can override specific schema fields if needed
metadata:
  extra_embeddings:
    - title
