apiVersion: v2
name: internal-perplexity
description: A Helm chart for deploying Milvus, OpenWebUI with pipelines, and Ollama
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: milvus
    version: "4.2.49" # Example updated version, check the Milvus Helm chart repository
    repository: "https://zilliztech.github.io/milvus-helm/"
    condition: milvus.enabled
  - name: open-webui
    version: "6.17.0" # Example updated version, check the Open WebUI Helm chart repository
    repository: "https://open-webui.github.io/helm-charts"
    condition: open-webui.enabled
  - name: ollama
    version: "1.18.0"
    repository: "https://otwld.github.io/ollama-helm/"
    condition: ollama.enabled

maintainers:
  - name: MeatheadMathematician
    email: matt@MeatheadMathematician.com

keywords:
  - milvus
  - open-webui
  - ollama
  - llm
  - vector-database
  - vector-search
  - ai
