replicaCount: 1
image:
  repository: ghcr.io/open-webui/open-webui
  tag: "latest"
service:
  type: ClusterIP
  port: 8080
persistence:
  enabled: true
  size: 2Gi
  storageClass: "microk8s-hostpath"
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: webui.{{ .Values.global.domain }}.nip.io
      paths:
        - path: /
          pathType: Prefix
ollama:
  enabled: false
ollamaurls:
  - ollama.{{ .Values.global.domain }}.nip.io
