# Global settings
global:
  storageClass: "microk8s-hostpath"
  domain: "YOUR_IP_ADDRESS"

# Milvus configuration
milvus:
  enabled: true
  mode: standalone
  storageClass: "microk8s-hostpath"
  persistence:
    enabled: true
    size: 5Gi
  resources:
    requests:
      cpu: "2"
      memory: "8Gi"
    limits:
      cpu: "4"
      memory: "16Gi"
  ingress: # TODO: Use this to access the Milvus dashboard
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - host: milvus.{{ .Values.global.domain }}.nip.io
        paths:
          - path: /
            pathType: Prefix
  cluster:
    enabled: false  # Disable distributed mode
  standalone:
    enabled: true   # Enable standalone mode
    persistence:
      enabled: true
      mountPath: "/var/lib/milvus"
      size: 50Gi    # Adjust storage size as needed
  etcd:
    replicaCount: 1
    persistence:
      enabled: true
      size: 10Gi
  minio:
    mode: standalone
    persistence:
      enabled: true
      size: 20Gi
  pulsar:
    enabled: false  # Disable Pulsar (standalone uses RocksMQ by default)


# OpenWebUI configuration
openwebui:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/open-webui/open-webui
    tag: "latest"
  service:
    type: ClusterIP
    port: 8080
  persistence:
    enabled: true
    size: 2Gi
    storageClass: "microk8s-hostpath"
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - host: webui.{{ .Values.global.domain }}.nip.io
        paths:
          - path: /
            pathType: Prefix
  ollama:
    enabled: false
  ollamaurls: [ollama.{{ .Values.global.domain }}.nip.io]

# Ollama configuration - we'll create this as a custom deployment
ollama:
  enabled: true
  image:
    repository: ollama/ollama
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 11434
  persistence:
    enabled: true
    size: 10Gi
    storageClass: "microk8s-hostpath"
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi
  gpu:
    enabled: false
  models:
    pull:
      - gemma3  
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - host: ollama.{{ .Values.global.domain }}.nip.io
        paths:
          - path: /
            pathType: Prefix